/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTerminalRouteImport } from './routes/_app.terminal'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppJewelleryRouteImport } from './routes/_app.jewellery'
import { Route as AppBankRouteImport } from './routes/_app.bank'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppJewelleryRoute = AppJewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bank': typeof AppBankRoute
  '/jewellery': typeof AppJewelleryRoute
  '/more': typeof AppMoreRoute
  '/orders': typeof AppOrdersRoute
  '/terminal': typeof AppTerminalRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bank': typeof AppBankRoute
  '/jewellery': typeof AppJewelleryRoute
  '/more': typeof AppMoreRoute
  '/orders': typeof AppOrdersRoute
  '/terminal': typeof AppTerminalRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/jewellery': typeof AppJewelleryRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/terminal': typeof AppTerminalRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/sitemap.xml'
    | '/bank'
    | '/jewellery'
    | '/more'
    | '/orders'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/audit'
    | '/sitemap.xml'
    | '/bank'
    | '/jewellery'
    | '/more'
    | '/orders'
    | '/terminal'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/audit'
    | '/sitemap.xml'
    | '/_app/bank'
    | '/_app/jewellery'
    | '/_app/more'
    | '/_app/orders'
    | '/_app/terminal'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal': {
      id: '/_app/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jewellery': {
      id: '/_app/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof AppJewelleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppJewelleryRoute: typeof AppJewelleryRoute
  AppMoreRoute: typeof AppMoreRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppJewelleryRoute: AppJewelleryRoute,
  AppMoreRoute: AppMoreRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
